services:

  mysql:
    image: mysql:8.4
    container_name: gitdoctor-mysql
    environment:
      MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD}
      MYSQL_DATABASE: ${MYSQL_DATABASE}
    ports:
      - "${MYSQL_PORT}:3306"
    volumes:
      - mysql_data:/var/lib/mysql
      - ./database/schema.sql:/docker-entrypoint-initdb.d/schema.sql

  backend:
    build: ./backend
    container_name: gitdoctor-backend
    ports:
      - "5000:5000"
    env_file:
      - .env
    depends_on:
      - mysql

  frontend:
    build: ./frontend
    container_name: gitdoctor-frontend
    ports:
      - "3000:80"
    depends_on:
      - backend

volumes:
  mysql_data: